apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  template:
    spec:
      containers:
        - name: srv
          image: xmlking/greeter-srv:latest
          imagePullPolicy: Always
          ports:
            - name: grpc-port
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
          envFrom:
            - configMapRef:
                name: env-vars
            - configMapRef:
                name: env-vars-common
            - secretRef:
                name: secrets
      volumes:
        - name: config
          configMap:
            name: config
