namespace: default
namePrefix: staging-

commonLabels:
  environment: staging
commonAnnotations:
  note: Hello, I am staging!

bases:
  - ../../bases

configMapGenerator:
  - behavior: merge
    files:
      - config/config.yaml
    name: configs

secretGenerator:
  - behavior: replace
    literals:
      - postgres-password=postgres123
    name: postgres-secrets

    images:
  - name: xmlking/account-srv
    newTag: v1.0.1
  - name: docker.io/bitnami/postgresql
    newTag: 10.7.0
