commonLabels:
  app.kubernetes.io/name: proxy
  app.kubernetes.io/instance: proxy-abcxzy
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

namePrefix: proxy

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=proxy-service
      # - MICRO_SERVER_ADVERTISE="$(PROXY_SERVICE_ENDPOINT):8081"

vars:
  - name: PROXY_SERVICE_ENDPOINT
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
