apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)
namePrefix: prod-
nameSuffix: -v1

commonLabels:
  environment: production
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases/micros
  - ../../bases/etcd

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/health-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  - path: patches/health-sidecar-only-for-proxy.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=proxy
  # - path: patches/resource_limit.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_LOG_LEVEL=info
      # profile specific variables
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS="$(ETCD_SRV_ENDPOINT)-client"
      - MICRO_REGISTER_TTL="60"
      - MICRO_REGISTER_INTERVAL="30"

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass

replicas:
  - name: srv
    count: 1

images:
  - name: etcd
    newTag: 3.3.15
  - name: postgres
    newTag: 11.5-alpine
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v1.15.1
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
