apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: secrets
  app.kubernetes.io/instance: secrets-abcxzy
  app.kubernetes.io/component: infra

secretGenerator:
#  - name: registry-credentials
#    files:
#      - ".dockerconfigjson=docker.secret.json"
#    type: kubernetes.io/dockerconfigjson
  - name: certs
    files:
      - ../../certs/ca-cert.pem
      - ../../certs/proxy-cert.pem
      - ../../certs/proxy-key.pem
      - ../../certs/upstream-ca-cert.pem
      - ../../certs/upstream-cert.pem
      - ../../certs/upstream-key.pem

    type: Opaque
