database:
  dialect: 3 # unspecified = 0, postgres = 1, mysq2 = 2, sqlite3 =3
  host: 0.0.0.0
  port: 9999
  username: sumo
  password: demo
#  database: "file:foobar?mode=memory&cache=shared"
  database: "file::memory:?cache=shared"
  max_open_conns: 1
  max_idle_conns: 1
  conn_max_lifetime: 1h
  logging: true
email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  email_server: smtp.gmail.com
  port: 587
  from: from@gmail.com

services:
  account:
    endpoint: tcp://account:8080
    version: v0.1.0
  greeter:
    endpoint: tcp://greeter:8081
#    endpoint: unix:///tmp/greeter.sock
    version: v0.1.0
  emailer:
    endpoint: tcp://emailer:8082
    version: v0.1.0
  recorder:
    endpoint: tcp://recorder:8083
    version: v0.1.0

features:
  metrics:
    address: prometheus:8125
    flush_interval: 1000000000
    enabled: false
  tracing:
    address: jaeger:6831
    flush_interval: 5000000000
    enabled: false
  tls:
    cert_file: /config/certs/upstream-localhost-cert.pem
    key_file: /config/certs/upstream-localhost-key.pem
    ca_file: /config/certs/upstream-ca-cert.pem
    servername: "localhost"
    enabled: false
  validator:
    enabled: true
  reqlogs:
    enabled: true
  translogs:
    topic: mkit.service.recorder
    enabled: true
