apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)

commonLabels:
  environment: integration
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am integration!

bases:
  - ../../bases/micros

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=integration
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - MICRO_LOG_LEVEL=debug
      # profile specific variables
      - MICRO_REGISTER_TTL="60"
      - MICRO_REGISTER_INTERVAL="30"
      # - MICRO_SELECTOR=static # static/memory still not working with gateway & proxy
      # - MICRO_REGISTRY=memory
      # following endpoint overwrites (in config.yaml) should be enabled only when  MICRO_SELECTOR=static is used.
      # - SERVICES_ACCOUNTSRV_ENDPOINT=$(ACCOUNT_SRV_ENDPOINT)
      # - SERVICES_GREETERSRV_ENDPOINT=$(GREETER_SRV_ENDPOINT)
      # - SERVICES_EMAILERSRV_ENDPOINT=$(EMAILER_SRV_ENDPOINT)
      # - SERVICES_RECORDERSRV_ENDPOINT=$(RECORDER_SRV_ENDPOINT)
      # - SERVICES_GATEWAYSRV_ENDPOINT=$(GATEWAY_SRV_ENDPOINT)
      # - SERVICES_PROXYSRV_ENDPOINT=$(PROXY_SRV_ENDPOINT)
      # - FEATURES_MTLS_ENABLED=true
      # - INSECURE_SKIP_VERIFY=true
      - FEATURES_REQLOGS_ENABLED=true

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=e2e-real-pass
  # - name: registry-credentials
  #   files:
  #       - ".dockerconfigjson=docker.secret.json"
  #   type: kubernetes.io/dockerconfigjson

replicas:
  - name: srv
    count: 1

images:
  - name: etcd
    newTag: 3.3.18
  - name: quay.io/coreos/etcd-operator
    newName: docker.pkg.github.com/cbws/etcd-operator/operator
    newTag: v0.10.0
  - name: postgres
    newTag: 11.5-alpine
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v2.0.0
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/recorder-srv
    newTag: $(IMAGE_VERSION)
