apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)

commonLabels:
  environment: integration
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am integration!

bases:
  - ../../bases/service

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=integration
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - MICRO_LOG_LEVEL=debug
      # profile specific variables
      - MICRO_REGISTER_TTL="60"
      - MICRO_REGISTER_INTERVAL="30"
      # - MICRO_SELECTOR=static # static/memory still not working with gateway & proxy
      # - MICRO_REGISTRY=memory
      # following endpoint overwrites (in config.yaml) should be enabled only when  MICRO_SELECTOR=static is used.
      # - SERVICES_ACCOUNT_ENDPOINT=$(ACCOUNT_SERVICE_ENDPOINT)
      # - SERVICES_GREETER_ENDPOINT=$(GREETER_SERVICE_ENDPOINT)
      # - SERVICES_EMAILER_SERVICE_ENDPOINT=$(EMAILER_SERVICE_ENDPOINT)
      # - SERVICES_RECORDER_ENDPOINT=$(RECORDER_SERVICE_ENDPOINT)
      # - FEATURES_MTLS_ENABLED=true
      # - INSECURE_SKIP_VERIFY=true
      - FEATURES_REQLOGS_ENABLED=true

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=e2e-real-pass
  # - name: registry-credentials
  #   files:
  #       - ".dockerconfigjson=docker.secret.json"
  #   type: kubernetes.io/dockerconfigjson

replicas:
  - name: service
    count: 1

images:
  - name: redis
    newTag: 5.0.9
  - name: quay.io/coreos/etcd
    newTag: v3.4.9
  - name: quay.io/coreos/etcd-operator
    newName: xmlking/etcd-operator
    newTag: v0.10.1
  - name: postgres
    newTag: 11.5-alpine
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v2.0.0
  - name: xmlking/account-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/recorder-service
    newTag: $(IMAGE_VERSION)
