apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-sidecar
spec:
  template:
    spec:
      containers:
        - name: health
          image: micro/micro:latest
          args:
            - "health"
            - "--address=:8088"
            - "--check_service=$(MICRO_SERVER_NAME)"
            - "--check_address=0.0.0.0:8080"
          envFrom:
            - configMapRef:
                name: env-vars
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
