apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: micro-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["configs"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "micro-role"
subjects:
  - kind: ServiceAccount
    name: micro
    namespace: default
