apiVersion: "etcd.database.coreos.com/v1beta2"
kind: EtcdCluster
metadata:
  name: etcd-cluster
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.4.3"
  repository: "quay.io/coreos/etcd"
  pod:
    labels:
      application: micro
    busyboxImage: "busybox:1.28.0-glibc"
