apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Please don't change the namespace field
#namespace: $(NS)
namespace: development
namePrefix: dev-
nameSuffix: -v1

commonLabels:
  environment: development
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am development!

resources:
  - ../../base/service
  - ../../base/etcd

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
#  - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_LOG_LEVEL=info
      # profile specific variables
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS="$(ETCD_SERVICE_ENDPOINT)-client"
      - MICRO_REGISTER_TTL="60"
      - MICRO_REGISTER_INTERVAL="30"
      - GRPC_GO_LOG_SEVERITY_LEVEL="info"
      - GRPC_GO_LOG_VERBOSITY_LEVEL="99"
      # - FEATURES_MTLS_ENABLED=true
      # - INSECURE_SKIP_VERIFY=true
      - FEATURES_REQLOGS_ENABLED=false

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=dev-real-pass

# labels for generated secrets at this level
#generatorOptions:
#  disableNameSuffixHash: true

replicas:
  - name: service
    count: 1

images:
  - name: redis
    newTag: 5.0.9
  - name: quay.io/coreos/etcd
    newTag: v3.4.9
  - name: quay.io/coreos/etcd-operator
    newName: xmlking/etcd-operator
    newTag: v0.10.1
  - name: postgres
    newTag: 11.5-alpine
  - name: envoyproxy/envoy-alpine
    newName: docker.io/envoyproxy/envoy-alpine
    newTag: v1.14.2
  - name: micro/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: v2.0.0
  - name: xmlking/account-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-service
    newTag: $(IMAGE_VERSION)
  - name: xmlking/recorder-service
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/recorder-service
    newTag: $(IMAGE_VERSION)
