commonLabels:
  app.kubernetes.io/name: greeter
  app.kubernetes.io/instance: greeter-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: greeter

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.yaml
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=mkit.service.greeter
      # - MICRO_SERVER_ADVERTISE="$(GREETER_SERVICE_ENDPOINT):8080"

vars:
  - name: GREETER_SERVICE_ENDPOINT
    objref:
      kind: Service
      name: service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
